apiVersion: v1
data:
  clientSecret: SEw5WndBVnJaMkZJMEw4V2hUNkd6RDl3cmlGbjBqYXE=
kind: Secret
metadata:
  creationTimestamp: "2025-07-18T05:03:43Z"
  labels:
    app.kubernetes.io/part-of: argocd
  name: keycloak-secret
  namespace: argocd
  resourceVersion: "19251"
  uid: b5581d3b-4705-4038-b867-a818182f9275
type: Opaque
